### PR TITLE
fix: Allow URL-encoded slashes in IDs

### LINKED ISSUE #20: URL-encoded slashes don't work for vault IDs or document IDs
If your vault ID or document ID contains a slash, the resulting location that will be returned from the server will be unreachable since the slash breaks the path. Even if the slash is urlencoded as `%2F`, it still can't be reached.

This seems to be an inherent issue in the Go net/url and so this issue carries over to the Gorilla mux package. See https://github.com/gorilla/mux/issues/77 for details.

There is a workaround: call mux.useEncodedPath() before starting the router.

We will also probably want to urlencode the returned location in the response so that it's actually usable as well.

### PR DESCRIPTION
**Pull request by DRK3**
closes #20

Fixed an issue that was preventing URL-encoded slashes from being used in IDs.

Made some adjustments to returned error codes and function names to improve spec compliance.

Did some minor refactoring and formatting.

Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

### CODE REVIEW

File: pkg/client/edv/client.go [hunk 1]
```diff
@@ -90,15 +91,32 @@ func (c *Client) sendPostJSON(objectToMarshal interface{}, endpoint, statusConfl
...
+	case http.StatusConflict:
 		return "", errors.New(statusConflictErrText)
+	default:
+		if resp.StatusCode != http.StatusCreated {
+			respText, err := ioutil.ReadAll(resp.Body)
+			if err != nil {
+				return "", fmt.Errorf("unable to read response: %w", err)
+			}
+
+			return "", errors.New(string(respText))
```
Comment (sudeshrshetty) [inline pkg/client/edv/client.go]: fmt.Errorf("%s", respText)

File: pkg/client/edv/client.go [hunk 2]
```diff
@@ -90,15 +91,32 @@ func (c *Client) sendPostJSON(objectToMarshal interface{}, endpoint, statusConfl
...
+		}
 	}
 
 	return resp.Header.Get("Location"), nil
 }
 
+func closeBody(resp *http.Response) {
```
Comment (sudeshrshetty) [inline pkg/client/edv/client.go]: minor : closeBody(respBody io.ReadCloser)

File: pkg/client/edv/client_test.go [hunk 3]
```diff
@@ -28,10 +28,22 @@ import (
...
+	testVaultID               = "testvault"
+	testVaultIDWithSlashes    = "http://example.com/" + testVaultID
+	testDocumentID            = "testdocument"
+	testDocumentIDWithSlashes = "http://example.com/" + testDocumentID
 )
 
+type failingReadCloser struct{}
+
+func (f failingReadCloser) Read(p []byte) (n int, err error) {
+	return 0, errors.New("failingReadCloser always fails")
```
Comment (sudeshrshetty) [inline pkg/client/edv/client_test.go]: fmt.Errorf vs errors.New

File: pkg/restapi/edv/operation/operations.go [hunk 4]
```diff
@@ -99,14 +101,15 @@ func (c *Operation) createDataVaultHandler(rw http.ResponseWriter, req *http.Req
 
 		_, err = rw.Write([]byte(fmt.Sprintf("Data vault creation failed: %s", err)))
 		if err != nil {
-			log.Errorf("Failed to write response for data vault creation failure: %s",
-				err.Error())
+			log.Errorf("Failed to write response for data vault creation failure: %s", err.Error())
```
Comment (sudeshrshetty) [inline pkg/restapi/edv/operation/operations.go]: Not writing error to response? or sending error response code?

File: pkg/restapi/edv/operation/operations.go [hunk 5]
```diff
@@ -119,15 +122,25 @@ func (c *Operation) createDocumentHandler(rw http.ResponseWriter, req *http.Requ
...
+	if err != nil {
+		rw.WriteHeader(http.StatusInternalServerError)
+
+		_, err = rw.Write([]byte(fmt.Sprintf("unable to escape vault ID path variable: %s", err.Error())))
+		if err != nil {
+			log.Errorf("Failed to write response for vault ID unescaping failure: %s", err.Error())
+		}
+
+		return
+	}
```
Comment (sudeshrshetty) [inline pkg/restapi/edv/operation/operations.go]: I see similar block is repeated many times in this file, follow [this](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/restapi/operation/common/operation.go#L163) pattern

File: pkg/client/edv/client.go [hunk 6]
```diff
@@ -32,52 +33,52 @@ func New(edvServerURL string) *Client {
...
-func getDocumentFromResponse(resp *http.Response) ([]byte, error) {
-	respData, err := ioutil.ReadAll(resp.Body)
+	respBytes, err := ioutil.ReadAll(resp.Body)
 	if err != nil {
 		return nil, fmt.Errorf("failed to read response message while retrieving document: %w", err)
 	}
 
-	return respData, nil
-}
+	serverEndpointReached := string(respBytes) == "specified document does not exist" ||
```
[the remark this answers is not in the document]
Comment (DRK3) [reply pkg/client/edv/client.go]: done. Also updated anywhere else that references those strings to use the constants

File: pkg/client/edv/client.go [hunk 7]
```diff
@@ -32,52 +33,52 @@ func New(edvServerURL string) *Client {
...
-
-	return getDocumentFromResponse(resp)
-}
-
-func getDocumentFromResponse(resp *http.Response) ([]byte, error) {
-	respData, err := ioutil.ReadAll(resp.Body)
+	respBytes, err := ioutil.ReadAll(resp.Body)
 	if err != nil {
 		return nil, fmt.Errorf("failed to read response message while retrieving document: %w", err)
 	}
```
[the remark this answers is not in the document]
Comment (DRK3) [reply pkg/client/edv/client.go]: done

File: pkg/client/edv/client.go (hunk 1 above)
Comment (DRK3) [reply pkg/client/edv/client.go]: done. I also updated everywhere else in this project to use fmt.Errorf

File: pkg/client/edv/client.go (hunk 2 above)
Comment (DRK3) [reply pkg/client/edv/client.go]: done

File: pkg/client/edv/client_test.go (hunk 3 above)
Comment (DRK3) [reply pkg/client/edv/client_test.go]: done

File: pkg/restapi/edv/operation/operations.go (hunk 5 above)
Comment (DRK3) [reply pkg/restapi/edv/operation/operations.go]: done

File: pkg/restapi/edv/operation/operations.go (hunk 4 above)
Comment (DRK3) [reply pkg/restapi/edv/operation/operations.go]: This error is a result of the **responseWriter itself failing** - so the best I can do is log.

Comment (DRK3) [reply pkg/restapi/edv/operation/operations.go]: (trying to write a response again would result in another error check...and then another error check for that error and so on and so forth)

File: pkg/client/edv/client.go [hunk 8]
```diff
@@ -32,52 +33,51 @@ func New(edvServerURL string) *Client {
...
 
-	return respData, nil
-}
+	if resp.StatusCode == http.StatusOK {
+		return respBytes, nil
+	} else if resp.StatusCode == http.StatusNotFound {
+		serverEndpointReached := string(respBytes) == operation.VaultNotFoundErrMsg ||
```
Comment (sudeshrshetty) [inline pkg/client/edv/client.go]: converting bytes to string is probably expensive, convert it once pass it on to some private fuction to make it cleaner/readable.

Comment (sudeshrshetty) [reply pkg/client/edv/client.go]: something like 

if resp.StatusCode == http.StatusOK {
}			return respBytes, nil
	} 
else if resp.StatusCode == http.StatusNotFound {
 return checkStatusNotFoundErr()
} else {
//return that generic error
}
`

File: pkg/client/edv/client.go [hunk 9]
```diff
@@ -32,52 +33,52 @@ func New(edvServerURL string) *Client {
...
 
-// RetrieveDocument sends the EDV server a request to retrieve the specified document.
+// ReadDocument sends the EDV server a request to retrieve the specified document.
 // The requested document is returned.
-func (c *Client) RetrieveDocument(vaultID, docID string) ([]byte, error) {
-	resp, err := http.Get(c.edvServerURL + "/encrypted-data-vaults/" + vaultID + "/docs/" + docID)
+func (c *Client) ReadDocument(vaultID, docID string) ([]byte, error) {
+	// The linter falsely claims that the body is not being closed
+	// https://github.com/golangci/golangci-lint/issues/637
+	resp, err := http.Get(c.edvServerURL + "/encrypted-data-vaults/" + //nolint: bodyclose
```
[the remark this answers is not in the document]
Comment (DRK3) [reply pkg/client/edv/client.go]: done

File: cmd/edv-rest/startcmd/start.go [hunk 10]
```diff
@@ -89,6 +89,7 @@ func startEDV(parameters *edvParameters) error {
 
 	handlers := edvService.GetOperations()
 	router := mux.NewRouter()
+	router.UseEncodedPath()
```
Comment (DRK3) [inline cmd/edv-rest/startcmd/start.go]: (this is what allowed the router to properly handle url-encoded strings in the path)

File: pkg/restapi/edv/operation/operations.go [hunk 11]
```diff
@@ -236,11 +257,29 @@ func (c *Operation) registerHandler() {
...
+// Returns the unescaped version of the path variable and a bool indicating whether the unescaping was successful.
+func unescapePathVar(pathVar string, vars map[string]string, rw http.ResponseWriter) (string, bool) {
+	unescapedPathVar, err := url.PathUnescape(vars[pathVar])
+	if err != nil {
+		rw.WriteHeader(http.StatusInternalServerError)
+
+		_, err = rw.Write([]byte(fmt.Sprintf("unable to escape %s path variable: %s", pathVar, err.Error())))
+		if err != nil {
+			log.Errorf("Failed to write response for %s unescaping failure: %s", pathVar, err.Error())
+		}
```
Comment (sudeshrshetty) [inline pkg/restapi/edv/operation/operations.go]: should be in some common sendError(code, msg) function, I see this is repeated in many places.
